name: Quality Check
on:
  push:
    pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  backend:
    name: Backend Quality Check
    runs-on: ubuntu-latest
    if: github.event.head_commit.modified[0] == 'backend'
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn install
      - name: 'Run prettier'
        working-directory: ./backend
        run: yarn prettier
      - name: 'Run eslint'
        working-directory: ./backend
        run: yarn lint

  frontend:
    name: Frontend Quality Check
    runs-on: ubuntu-latest
    if: github.event.head_commit.modified[0] == 'frontend'
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn install
      - name: 'Run prettier'
        working-directory: ./frontend
        run: yarn prettier
      - name: 'Run eslint'
        working-directory: ./frontend
        run: yarn lint
